name: ruff
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: pip install --user ruff
    - run: ruff check --output-format=github --target-version=py38 .
